language: python
python:
  - "2.7"
  - "3.6"
  - "nightly"
install:
  - pip install flake8
  - pip install radon
script:
  - flake8 --ignore=E501  # ignore "line too long errors"
  - radon cc ./diary/ -a
  - radon mi .
  - radon raw . -s
